db: 'postgres://postgres:password@db:5432/postgres?sslmode=disable'
exchanges:
  bybit:
    rest_api_url: 'https://api.bybit.com/v5/market/kline'
    ws_api_url: 'wss://stream.bybit.com/v5/public/spot'
    category: 'spot'
    startSince: 1738368000000
    tickers:
      BTCUSDT: 'BTC_USDT'
      ETHUSDT: 'ETH_USDT'
      BCHUSDT: 'BCH_USDT'
    timeframes:
      1: 60000
      15: 900000
      60: 3600000
      D: 86400000
