db: 'postgres://postgres:password@localhost:6432/postgres?sslmode=disable'
exchanges:
  bybit:
    rest_api_url: 'https://api.bybit.com/v5/market/kline'
    ws_api_url: 'wss://stream.bybit.com/v5/public/spot'
    tickers:
      BTC_USDT: 'BTCUSDT'
      ETH_USDT: 'ETHUSDT'
      BCH_USDT: 'BCHUSDT'
    timeframes:
      1: 60000
      15: 900000
      60: 3600000
      D: 86400000
