db: 'postgres://postgres:password@localhost:6432/postgres?sslmode=disable'
exchanges:
  bybit:
    rest_api_url: 'https://api.bybit.com/v5/market/kline'
    ws_api_url: 'wss://stream.bybit.com/v5/public/spot'
    category: 'spot'
    tickers:
      BTCUSDT: 'BTC_USDT'
    timeframes:
      1: 60000
